### ISSUE TITLE
Copyrights

### ISSUE THREAD

**Issue by MishimaHaruna** [RagEmu/Renewal#6]
Hello

Commit a9bf058d7e9551f11f40e44265d0e5ebb94ca3ae (and possibly others) are in violation of the Hercules copyrights. Could you please fix that? No matter what you do, as long as there is copyrighted code on the file, you shouldn't remove a copyright line. Thank you

**Comment by Michieru** [comment]
Add it here:
https://github.com/RagEmu/Renewal/commit/02a772eedd7e07c61dc5de7d58407ff2ac13ebf3

**Comment by MishimaHaruna** [comment]
Thank you
